services:
    influx-db:
        image: influxdb
        volumes:
            - ./.influx/data:/var/lib/influxdb2
            - ./.influx/config:/etc/influxdb2
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=dev
            - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
            - DOCKER_INFLUXDB_INIT_ORG=dev
            - DOCKER_INFLUXDB_INIT_BUCKET=dev
        ports:
            - 8086:8086
